max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Auto"
use_small_heuristics = "Max"
indent_style = "Block"
match_block_trailing_comma = true
trailing_comma = "Vertical"
trailing_semicolon = true
reorder_imports = true
reorder_modules = true
group_imports = "StdExternalCrate"
format_strings = true
format_macro_matchers = true
format_macro_bodies = true
empty_item_single_line = true
struct_lit_single_line = true
fn_single_line = false
where_single_line = false
imports_indent = "Block"
imports_granularity = "Crate"
normalize_comments = false
normalize_doc_attributes = false
wrap_comments = true
comment_width = 100
edition = "2021"
version = "Two"