use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum Element {
    H,
    He,
    C,
    N,
    O,
    F,
    Na,
    Mg,
    Al,
    Si,
    P,
    S,
    Cl,
    K,
    Ca,
    Ti,
    Cr,
    Mn,
    Fe,
    Ni,
    Cu,
    Zn,
    As,
    Br,
    Ag,
    I,
    Au,
    Hg,
    Pb,
    U,
    Pu,
}

impl Element {
    pub fn atomic_number(&self) -> u8 {
        match self {
            Self::H => 1,
            Self::He => 2,
            Self::C => 6,
            Self::N => 7,
            Self::O => 8,
            Self::F => 9,
            Self::Na => 11,
            Self::Mg => 12,
            Self::Al => 13,
            Self::Si => 14,
            Self::P => 15,
            Self::S => 16,
            Self::Cl => 17,
            Self::K => 19,
            Self::Ca => 20,
            Self::Ti => 22,
            Self::Cr => 24,
            Self::Mn => 25,
            Self::Fe => 26,
            Self::Ni => 28,
            Self::Cu => 29,
            Self::Zn => 30,
            Self::As => 33,
            Self::Br => 35,
            Self::Ag => 47,
            Self::I => 53,
            Self::Au => 79,
            Self::Hg => 80,
            Self::Pb => 82,
            Self::U => 92,
            Self::Pu => 94,
        }
    }

    pub fn atomic_mass(&self) -> f32 {
        match self {
            Self::H => 1.008,
            Self::He => 4.0026,
            Self::C => 12.011,
            Self::N => 14.007,
            Self::O => 15.999,
            Self::F => 18.998,
            Self::Na => 22.990,
            Self::Mg => 24.305,
            Self::Al => 26.982,
            Self::Si => 28.085,
            Self::P => 30.974,
            Self::S => 32.06,
            Self::Cl => 35.45,
            Self::K => 39.098,
            Self::Ca => 40.078,
            Self::Ti => 47.867,
            Self::Cr => 51.996,
            Self::Mn => 54.938,
            Self::Fe => 55.845,
            Self::Ni => 58.693,
            Self::Cu => 63.546,
            Self::Zn => 65.38,
            Self::As => 74.922,
            Self::Br => 79.904,
            Self::Ag => 107.868,
            Self::I => 126.904,
            Self::Au => 196.967,
            Self::Hg => 200.59,
            Self::Pb => 207.2,
            Self::U => 238.029,
            Self::Pu => 244.0,
        }
    }

    pub fn electronegativity(&self) -> f32 {
        match self {
            Self::H => 2.20,
            Self::He => 0.0,
            Self::C => 2.55,
            Self::N => 3.04,
            Self::O => 3.44,
            Self::F => 3.98,
            Self::Na => 0.93,
            Self::Mg => 1.31,
            Self::Al => 1.61,
            Self::Si => 1.90,
            Self::P => 2.19,
            Self::S => 2.58,
            Self::Cl => 3.16,
            Self::K => 0.82,
            Self::Ca => 1.00,
            Self::Ti => 1.54,
            Self::Cr => 1.66,
            Self::Mn => 1.55,
            Self::Fe => 1.83,
            Self::Ni => 1.91,
            Self::Cu => 1.90,
            Self::Zn => 1.65,
            Self::As => 2.18,
            Self::Br => 2.96,
            Self::Ag => 1.93,
            Self::I => 2.66,
            Self::Au => 2.54,
            Self::Hg => 2.00,
            Self::Pb => 1.87,
            Self::U => 1.38,
            Self::Pu => 1.28,
        }
    }

    pub fn radioactive(&self) -> bool {
        matches!(self, Self::U | Self::Pu)
    }

    pub fn half_life_years(&self) -> Option<f32> {
        match self {
            Self::U => Some(4.468e9),
            Self::Pu => Some(2.411e4),
            _ => None,
        }
    }

    pub fn symbol(&self) -> &str {
        match self {
            Self::H => "H",
            Self::He => "He",
            Self::C => "C",
            Self::N => "N",
            Self::O => "O",
            Self::F => "F",
            Self::Na => "Na",
            Self::Mg => "Mg",
            Self::Al => "Al",
            Self::Si => "Si",
            Self::P => "P",
            Self::S => "S",
            Self::Cl => "Cl",
            Self::K => "K",
            Self::Ca => "Ca",
            Self::Ti => "Ti",
            Self::Cr => "Cr",
            Self::Mn => "Mn",
            Self::Fe => "Fe",
            Self::Ni => "Ni",
            Self::Cu => "Cu",
            Self::Zn => "Zn",
            Self::As => "As",
            Self::Br => "Br",
            Self::Ag => "Ag",
            Self::I => "I",
            Self::Au => "Au",
            Self::Hg => "Hg",
            Self::Pb => "Pb",
            Self::U => "U",
            Self::Pu => "Pu",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum Compound {
    Water,
    CarbonDioxide,
    Methane,
    Ammonia,
    HydrogenPeroxide,
    SulfuricAcid,
    HydrochloricAcid,
    NitricAcid,
    SodiumHydroxide,
    CalciumCarbonate,
    IronOxide,
    SiliconDioxide,
    SodiumChloride,
    PotassiumNitrate,
    Glucose,
    Ethanol,
    AceticAcid,
    PhosphoricAcid,
    LeadSulfide,
    UraniumOxide,
    PlutoniumOxide,
    NitroCompound,
    Gunpowder,
    TNT,
    RDX,
    RadioactiveIsotope,
    BiologicalToxin,
    CorrosiveAgent,
    RadioactiveDust,
    ToxicSludge,
    Biofuel,
    MutagenCompound,
    Neurotoxin,
    Thermite,
    CryoAgent,
    AcidRain,
    RustInhibitor,
}

impl Compound {
    pub fn formula(&self) -> &str {
        match self {
            Self::Water => "H2O",
            Self::CarbonDioxide => "CO2",
            Self::Methane => "CH4",
            Self::Ammonia => "NH3",
            Self::HydrogenPeroxide => "H2O2",
            Self::SulfuricAcid => "H2SO4",
            Self::HydrochloricAcid => "HCl",
            Self::NitricAcid => "HNO3",
            Self::SodiumHydroxide => "NaOH",
            Self::CalciumCarbonate => "CaCO3",
            Self::IronOxide => "Fe2O3",
            Self::SiliconDioxide => "SiO2",
            Self::SodiumChloride => "NaCl",
            Self::PotassiumNitrate => "KNO3",
            Self::Glucose => "C6H12O6",
            Self::Ethanol => "C2H5OH",
            Self::AceticAcid => "CH3COOH",
            Self::PhosphoricAcid => "H3PO4",
            Self::LeadSulfide => "PbS",
            Self::UraniumOxide => "UO2",
            Self::PlutoniumOxide => "PuO2",
            Self::NitroCompound => "C3H5N3O9",
            Self::Gunpowder => "KNO3+S+C",
            Self::TNT => "C7H5N3O6",
            Self::RDX => "C3H6N6O6",
            Self::RadioactiveIsotope => "U-235",
            Self::BiologicalToxin => "C31H48N4O6",
            Self::CorrosiveAgent => "HF",
            Self::RadioactiveDust => "U3O8+PuO2",
            Self::ToxicSludge => "CxHyOz",
            Self::Biofuel => "C2H5OH+CH4",
            Self::MutagenCompound => "C15H22N2O5",
            Self::Neurotoxin => "C11H26NO2PS",
            Self::Thermite => "Fe2O3+Al",
            Self::CryoAgent => "N2O4",
            Self::AcidRain => "H2SO4+HNO3",
            Self::RustInhibitor => "Zn3(PO4)2",
        }
    }

    pub fn molar_mass(&self) -> f32 {
        match self {
            Self::Water => 18.015,
            Self::CarbonDioxide => 44.01,
            Self::Methane => 16.04,
            Self::Ammonia => 17.03,
            Self::HydrogenPeroxide => 34.01,
            Self::SulfuricAcid => 98.08,
            Self::HydrochloricAcid => 36.46,
            Self::NitricAcid => 63.01,
            Self::SodiumHydroxide => 40.00,
            Self::CalciumCarbonate => 100.09,
            Self::IronOxide => 159.69,
            Self::SiliconDioxide => 60.08,
            Self::SodiumChloride => 58.44,
            Self::PotassiumNitrate => 101.10,
            Self::Glucose => 180.16,
            Self::Ethanol => 46.07,
            Self::AceticAcid => 60.05,
            Self::PhosphoricAcid => 98.00,
            Self::LeadSulfide => 239.3,
            Self::UraniumOxide => 270.03,
            Self::PlutoniumOxide => 276.0,
            Self::NitroCompound => 227.09,
            Self::Gunpowder => 270.0,
            Self::TNT => 227.13,
            Self::RDX => 222.12,
            Self::RadioactiveIsotope => 235.0,
            Self::BiologicalToxin => 500.0,
            Self::CorrosiveAgent => 20.01,
            Self::RadioactiveDust => 842.0,
            Self::ToxicSludge => 180.0,
            Self::Biofuel => 50.0,
            Self::MutagenCompound => 294.35,
            Self::Neurotoxin => 267.37,
            Self::Thermite => 213.7,
            Self::CryoAgent => 92.01,
            Self::AcidRain => 120.0,
            Self::RustInhibitor => 386.11,
        }
    }

    pub fn category(&self) -> CompoundCategory {
        match self {
            Self::Water | Self::CarbonDioxide | Self::SiliconDioxide => CompoundCategory::Inert,
            Self::Methane | Self::Ethanol | Self::Glucose => CompoundCategory::Organic,
            Self::Ammonia | Self::HydrogenPeroxide => CompoundCategory::Reactive,
            Self::SulfuricAcid
            | Self::HydrochloricAcid
            | Self::NitricAcid
            | Self::PhosphoricAcid => CompoundCategory::Acid,
            Self::SodiumHydroxide => CompoundCategory::Base,
            Self::IronOxide
            | Self::CalciumCarbonate
            | Self::SodiumChloride
            | Self::PotassiumNitrate
            | Self::LeadSulfide => CompoundCategory::Mineral,
            Self::UraniumOxide | Self::PlutoniumOxide | Self::RadioactiveIsotope => {
                CompoundCategory::Radioactive
            },
            Self::Gunpowder | Self::TNT | Self::RDX | Self::NitroCompound => {
                CompoundCategory::Explosive
            },
            Self::AceticAcid => CompoundCategory::Acid,
            Self::BiologicalToxin => CompoundCategory::Toxin,
            Self::CorrosiveAgent => CompoundCategory::Corrosive,
            Self::RadioactiveDust | Self::ToxicSludge => CompoundCategory::Radioactive,
            Self::Biofuel => CompoundCategory::Organic,
            Self::MutagenCompound => CompoundCategory::Toxin,
            Self::Neurotoxin => CompoundCategory::Toxin,
            Self::Thermite => CompoundCategory::Explosive,
            Self::CryoAgent => CompoundCategory::Reactive,
            Self::AcidRain => CompoundCategory::Acid,
            Self::RustInhibitor => CompoundCategory::Mineral,
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum CompoundCategory {
    Inert,
    Organic,
    Reactive,
    Acid,
    Base,
    Mineral,
    Radioactive,
    Explosive,
    Toxin,
    Corrosive,
}
